name: decider
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  flutter_easyloading: ^3.0.5
  intl: ^0.20.2
  provider: ^6.1.5
  timer_count_down: ^2.2.2
  google_mobile_ads: ^5.3.1
  icons_launcher: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jsons/
    - assets/images/

icons_launcher:
  image_path: "assets/images/img-logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
